version: '3.8'

services:
  dify-quiz-chat:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DIFY_API_KEY=${DIFY_API_KEY}
      - DIFY_BASE_URL=${DIFY_BASE_URL:-https://api.dify.ai/v1}
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
      - DEBUG=False
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
